# Generated by Django 5.1.4 on 2026-08-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="father_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="is_registration_complete",
            field=models.BooleanField(
                default=False,
                help_text="True only after student face embeddings are successfully captured",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
