# Generated by Django 5.1.4 on 2026-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_normalize_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, help_text='School admission number for the student', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_registration_complete',
            field=models.BooleanField(default=False, help_text='True only after teacher face embeddings are successfully captured'),
        ),
    ]
