# Generated by Django 5.1.4 on 2026-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_daily_pdf_export', models.BooleanField(default=False, help_text="When enabled, a PDF attendance report for the previous day is generated automatically at the start of every new day and saved locally in the 'Attendance Reports' folder. Active users only.", verbose_name='Enable Automatic Daily PDF Export')),
                ('last_exported_report_date', models.DateField(blank=True, editable=False, help_text='Date of the last automatically generated daily report.', null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
